# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:           https://github.com/economistgame/poole/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/economistgame/poole
